{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}-deployment
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          {{- if or .Values.deployment.envFromConfigMap .Values.deployment.envFromSecret }}
          envFrom:
            {{- if and .Values.deployment.envFromConfigMap .Values.configMap.enabled }}
            - configMapRef:
                name: {{ include "mychart.fullname" . }}-config
            {{- end }}
            {{- if and .Values.deployment.envFromSecret .Values.secret.enabled }}
            - secretRef:
                name: {{ include "mychart.fullname" . }}-secret
            {{- end }}
          {{- end }}
{{- end }}
