{{- if .Values.pod.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "mychart.fullname" . }}-pod
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  containers:
    - name: app
      image: {{ .Values.pod.image }}
      volumeMounts:
        - name: scratch
          mountPath: /tmp/scratch
        - name: host-data
          mountPath: /data
  volumes:
    - name: scratch
      emptyDir: {}
    - name: host-data
      hostPath:
        path: {{ .Values.pod.hostPath.path }}
        type: {{ .Values.pod.hostPath.type }}
{{- end }}
