apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-api
  labels:
    app: appointment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-api
  template:
    metadata:
      labels:
        app: appointment-api
    spec:
      containers:
        - name: appointment-api
          image: dockeritc778/appointment-api:v1
          ports:
            - containerPort: 3001
