apiVersion: v1
kind: Service
metadata:
  name: appointment-api
  labels:
    app: appointment-api
spec:
  type: ClusterIP
  selector:
    app: appointment-api
  ports:
    - port: 3001
      targetPort: 3001
