apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-api
  labels:
    app: patient-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-api
  template:
    metadata:
      labels:
        app: patient-api
    spec:
      containers:
        - name: patient-api
          image: dockeritc778/patient-api:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 50Mi